# .github/workflows/build-api-db.yml
name: Build API + DACPAC and Deploy

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore & Publish API
        run: |
          dotnet restore .\PawRescue-backend\PawRescue-backend\PawRescue.API\PawRescue.API.csproj
          dotnet publish .\PawRescue-backend\PawRescue-backend\PawRescue.API\PawRescue.API.csproj -c Release -o .\out\api

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Ensure SSDT (Database Projects) is installed
        shell: powershell
        run: |
          $vsPath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          & "$vsPath\vs_installer.exe" modify --installPath "$vsPath" --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Component.SQL.SSDT --quiet --norestart
          # після цього з'явиться каталог ...\MSBuild\Microsoft\VisualStudio\v17.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets

      - name: Build DACPAC
        run: |
          msbuild .\PawRescue-backend\PawRescue-backend\PawRescue.Database\PawRescue.Database.sqlproj /t:Build /p:Configuration=Release

      - name: Find SqlPackage
        id: sqlpackage
        shell: powershell
        run: |
          $sp = Get-ChildItem "C:\Program Files\Microsoft SQL Server\*\DAC\bin\SqlPackage.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -Last 1
          if (-not $sp) { throw "SqlPackage.exe not found" }
          echo "path=$($sp.FullName)" >> $env:GITHUB_OUTPUT

      - name: Publish DACPAC to Azure SQL
        shell: powershell
        run: |
          $dacpac = ".\PawRescue-backend\PawRescue-backend\PawRescue.Database\bin\Release\PawRescue.Database.dacpac"
          & "${{ steps.sqlpackage.outputs.path }}" /Action:Publish /SourceFile:$dacpac `
            /TargetConnectionString:'${{ secrets.AZURE_SQL_CONNECTION_STRING }}' `
            /p:BlockOnPossibleDataLoss=false /p:GenerateSmartDefaults=true

      - name: Deploy API to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .\out\api
